CREATE TABLE roles(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CHECK (name IN ('STUDENT', 'TEACHER', 'PARENT', 'ADMIN'))
)