spring:
  application:
    name: edugo
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  secret-key: ${JWT_SECRET:dev-secret-key-change-in-production-32chars}
  expiration-ms: 900000
